### ISSUE TITLE
Make AcmeException unchecked

### ISSUE THREAD

**Issue by axelfontaine** [shred/acme4j#10]
This gives users a choice whether to catch it

**Comment by shred** [comment]
Checked exceptions are a controversial (and quite emotional) topic. Many Java developers think that checked exceptions are one of Javas biggest mistakes. I don't think so. On my work as a Java professional, I once too often found bugs that could have been avoided if the developer was forced to give exception handling a second thought. Making all exceptions RuntimeExceptions won't make them go away. They will usually just bubble up, and at some point end up in a log file or on a user dialog. :-)

Using a plain RuntimeException approach may be a good idea for frontend code. However, I think that on a lower level (e.g. libraries like acme4j), stricter rules should apply. I prefer to stick to the [Oracle bottom line](https://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html): "If a client can reasonably be expected to recover from an exception, make it a checked exception. If a client cannot do anything to recover from the exception, make it an unchecked exception."

After I read your issue, I have had a closer look at the AcmeExceptions and where I throw them. I think you are right in so far that _some_ checked exceptions should be avoided. For example, if the server returns unparseable JSON, it clearly should be a runtime exception, as there is obviously some broken program code where the client cannot recover from.

I am currently reviewing the acme4j exception handling...

**Comment by shred** [comment]
After the review, the 'AcmeClientFactory' does not throw checked exceptions any more. Generally, exceptions have been tidied up, with introducing a new unchecked 'AcmeProtocolException' for all kind of protocol errors that "should not happen" and cannot be recovered from anyways. However 'AcmeClient' still throws checked exceptions, for the reasons mentioned above.

I hope it is at least a little helpful for you. :wink: I am closing this bug now.
