### ISSUE TITLE
Intermediate certificate required. Unable to get issuer certificate.

### ISSUE THREAD

**Issue by scolastico** [shred/acme4j#116]
If i install the generated certificate from the cert chain i get this error in my browser and if i check the cert i get the message "Intermediate certificate required. Unable to get issuer certificate."

To save the cert i used the following (both result in the same error):
```
        Certificate cert = order.getCertificate();
        assert cert != null;
        StringBuilder builder = new StringBuilder();
        final Base64.Encoder encoder = Base64.getMimeEncoder(64, LINE_SEPARATOR.getBytes());
        for (X509Certificate certificate:cert.getCertificateChain()) {
          builder
              .append(BEGIN_CERT)
              .append(LINE_SEPARATOR)
              .append(new String(encoder.encode(certificate.getEncoded())))
              .append(LINE_SEPARATOR)
              .append(END_CERT)
              .append(LINE_SEPARATOR);
        }
        System.out.println(builder.toString());
        StringWriter certStringWriter = new StringWriter();
        cert.writeCertificate(certStringWriter);
```

![Screenshot 2021-06-03 122816](https://user-images.githubusercontent.com/26954501/120638455-6b450a00-c470-11eb-850c-bfbb9abd01bb.png)

**Comment by shred** [comment]
Your code looks okay on the first sight.

Let's Encrypt has recently changed its issuer certificate. My suspicion is that your server still delivers the old certificate chain along with your certificate, so the issuer of your certificate does not match.

Please check the certificate in your browser. The issuer of your certificate must match the next certificate in your certificate chain. If you use Let's Encrypt, the issuer should be named "R3".

**Comment by scolastico** [comment]
Yeah the software which uses the certificate isnt from me. I only generate certificate for it. I will open there also an ticket and will link this issue to it. Thank you @shred.

**Comment by shred** [comment]
Thank you for the feedback. I will close the issue for now. Feel free to reopen it when necessary.

**Comment by scolastico** [comment]
Sure. Btw i also checked the cert seems like its all ok with it and you have right: only the web server does something wrong...
![image](https://user-images.githubusercontent.com/26954501/120672609-bff97c80-c492-11eb-9343-e23c324b2d9b.png)

**Comment by shred** [comment]
Ahhh... You are using the Let's Encrypt STAGING server. It does not provide certificates that are usable in a browser.

For production, you need to use the production server of Let's Encrypt.

In the example it is `Session session = new Session("acme://letsencrypt.org");`

**Comment by scolastico** [comment]
Oh wow i used it because of the documentation: 
![image](https://user-images.githubusercontent.com/26954501/120676245-1d42fd00-c496-11eb-98bb-9e08ce672fee.png)

Then i think so nobody else does the same mistake like i did the documentation should be updated with a warning or a tip to adress this issue.
