### ISSUE TITLE
Remove service loader mechanism

### ISSUE THREAD

**Issue by Maurice-Betzel** [shred/acme4j#131]
Hi,

the service loader mechanism in the Session class is imo not really needed as there are few ACME providers that need to deviate from the standard protocol, it complicates usage of the library, especially in OSGi.

**Comment by shred** [comment]
Hi!

It's true that I was hoping for more ACME providers. :wink: But the service loader is an integral part of Java Modules, so I don't see a good reason why it should not be used.

As a compromise, would it help you if the Let's Encrypt provider gets hardwired into acme4j (so it won't be loaded via service loader), but I keep the service loader mechanism as an option for other providers?

**Comment by Maurice-Betzel** [comment]
Let me think about an acme4j OSGi maven module add on, using the Spi Fly OSGi service loader bridge.

**Comment by Maurice-Betzel** [comment]
I have created invasion free solution with the Aries SPI FLY dynamic service loading mechanism.
Install Aries SPI FLY, or other OSGi Java service provider bridge, and create a bundle fragment to extend the headers on the acme4j-client like this to let SPI FLY register the providers:

    <dependencies>
        <dependency>
            <groupId>org.shredzone.acme4j</groupId>
            <artifactId>acme4j-client</artifactId>
            <version>${shredzone.acme4j.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <configuration>
                    <instructions>
                        <Fragment-Host>acme4j-client</Fragment-Host>
                        <Require-Capability>
                            osgi.extender;
                            filter:="(osgi.extender=osgi.serviceloader.registrar)"
                        </Require-Capability>
                        <Provide-Capability>
                            osgi.serviceloader;
                            uses:="org.shredzone.acme4j.provider";
                            osgi.serviceloader=org.shredzone.acme4j.provider.AcmeProvider
                        </Provide-Capability>
                    </instructions>
                </configuration>
            </plugin>
        </plugins>
    </build>

On the bundle creating the session, being the consumer of the above providers, declare the following:

    <dependencies>
        <dependency>
            <groupId>org.shredzone.acme4j</groupId>
            <artifactId>acme4j-client</artifactId>
            <version>${shredzone.acme4j.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.quartz-scheduler</groupId>
            <artifactId>quartz</artifactId>
            <version>${quartz.scheduler.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <configuration>
                    <instructions>
                        <Require-Capability>
                            osgi.serviceloader;
                            filter:="(osgi.serviceloader=org.shredzone.acme4j.provider.AcmeProvider)";
                            cardinality:=multiple,
                            osgi.extender;
                            filter:="(osgi.extender=osgi.serviceloader.processor)"
                        </Require-Capability>
                    </instructions>
                </configuration>
            </plugin>
        </plugins>
    </build>

As you can see this is a api bundle containing my Quartz cron jobs.
Create the acme4j Session like below (see in the Session.class), because Quartz cannot access the Service Provider within the job running on an internal thread, that would need a ClassLoadingHelper and even more fiddling:

Iterable<AcmeProvider> providers = ServiceLoader.load(AcmeProvider.class);
        AcmeProvider provider = StreamSupport.stream(providers.spliterator(), false)
                .filter(p -> p.accepts(serverUri))
                .reduce((a, b) -> {
                    throw new IllegalArgumentException("Both ACME providers "
                            + a.getClass().getSimpleName() + " and "
                            + b.getClass().getSimpleName() + " accept "
                            + serverUri + ". Please check your classpath.");
                })
                .orElseThrow(() -> new IllegalArgumentException("No ACME provider found for " + serverUri));
        LOGGER.info("Triggering Let's Encrypt request certificate job from URL {}", serverUri);
        try {
            Session session = new Session(serverUri, provider);
            session.setLocale(Locale.UK);
            Metadata meta = session.getMetadata();
            URI termsOfService = meta.getTermsOfService();
            URL website = meta.getWebsite();
            LOGGER.info("ACME account URL {}", website);
