### ISSUE TITLE
Is there a way to keep txt unchanged and verify twice？

### ISSUE THREAD

**Issue by toxmc** [shred/acme4j#149]
As shown in the question，
I am trying to verify using DNS TXT mode.
And my local DNS verification passed, but due to the DNS txt record not being globally valid, CA verification failed. Is there a way to re-validate the TXT record instead of generating a new one

Wishing you a good day.

**Comment by shred** [comment]
No. If a challenge has failed, you need to start a new challenge with a new TXT record.

**Comment by toxmc** [comment]
thank you. I got it.
