### ISSUE TITLE
Bouncy Castel dependency?

### ISSUE THREAD

**Issue by hrstoyanov** [shred/acme4j#151]
Hello,
**This is not an issue**, but since the Discussions tab for this project is  not enabled, I wouldllike ask here is there a strong reason to be using Bouncy Castle rather than the built-in Java Cryptography Framework (Sorry, I only looked briefly at the code)? If not, any plans to remove this dependency?

**Comment by shred** [comment]
acme4j is currently using Bouncy Castle for these purposes:

* Generating a CSR for ordering a certificate
* Creating a X509Certificate for the tls-alpn-01 challenge
* All utility classes in the `org.shredzone.acme4j.util` package
* The acme4j-smime module makes extensive use of Bouncy Castle for parsing, validating, and creating S/MIME emails

I would like to remove the Bouncy Castle dependency, but unfortunately the Java Cryptography Framework offers no sufficient alternatives.

It is possible to avoid Bouncy Castle if you do not use the tls-alpn-01 challenge, the acme4j-smime module, and the utility classes. But when ordering a certificate, you would then have to create a CSR yourself by other means, and then invoke `Order.execute(byte[] csr)`.

**Comment by hrstoyanov** [comment]
Thanks!
...yes, I only need  HTTP-01 protocol. I am developing a Java Helidon  extension and trying to minimize external dependencies to the absolutely necessary minimum (similar to the ACEM plug-in  [IBM did for OpenLiberty](https://github.com/OpenLiberty/open-liberty/tree/d1f0e4e8064d91deef53dfc06700ea667d0bd4ee/dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme)). I Have not looked at IBM's  code, but I doubt they use Bouncy Castle ...

Another question  - any strong reason for using SLF4J instead of the [Java 9 Platform logging](https://openjdk.org/jeps/264), which serves the same reason a - a facade for othger logging frameworks (inlcluding SLF4J)

**Comment by shred** [comment]
I just had a quick look at IBM's OpenLiberty source, and they use acme4j. :laughing: They also use acme4j's `CSRBuilder`, so I am sure they use Bouncy Castle.

You could use OpenSSL for creating CSRs, but then you'll have a dependency to an external tool.

About logging: I will have a look at JEP 264 and check if it is an option to switch. I could remove a dependency that way, but I first have to make sure it won't break existing logging.

**Comment by hrstoyanov** [comment]
Thanks you for proving me wrong on IBM OpenLiberty! 

I just looked at some old code for generating CSR in Java [here](https://www.pixelstech.net/article/1464167276-Generating-CSR-using-Java)

**Comment by shred** [comment]
Your example uses a lot of `sun.*` packages, which are not part of the public Java API: https://www.oracle.com/java/technologies/faq-sun-packages.html

So this is not an option. However you could still use it in your code, and invoke `Order.execute(byte[] csr)` with the generated CSR.

**Comment by hrstoyanov** [comment]
Sorry .. yes sun.com.* stuff is not good (probably des not work on other JDKs ata ll). 

As for the logging .. [this is interesting](https://www.baeldung.com/java-9-logging-api)

**Comment by hrstoyanov** [comment]
Btw, feel free to close this issue.

**Comment by shred** [comment]
Discussions are enabled now. Thank you for the pointer.

Feel free to reopen if you found a way to remove the BC dependency.

**Comment by hrstoyanov** [comment]
Thank you @shred !
The arguments and justifications for you choices explained in the above thread are very solid, so I will use acme4j as is. If I discover a better replacement for bouncyc castle, I will bring it to your attention.
