### ISSUE TITLE
Provide example showing how to save and load existing certificates

### ISSUE THREAD

**Issue by cowwoc** [shred/acme4j#153]
Given that most (all?) ACME servers do not support listing existing certifications, please clarify how we are supposed to create a `Certificate` object without placing an `Order` with the ACME server.

We need to know what information needs to be saved, and how to use this information to construct a `Certificate` at a later time.

**Comment by shred** [comment]
Please see the answer I gave in issue 146: https://github.com/shred/acme4j/issues/146#issuecomment-1815934037

You need to store the certificate location somewhere.

```java
Certificate cert = // the certificate that was freshly created
URL certLocation = cert.getLocation();
// store certLocation somewhere
```

To reconstruct the `Certificate` instance from that location, bind it to a `Login`:

```java
Login login = // your login
URL certLocation = // certLocation that was stored

Certificate cert = login.bindCertificate(certLocation);
```

**Comment by cowwoc** [comment]
Works for me. Thank you.
