### ISSUE TITLE
Class org.bouncycastle.asn1.bc.BCObjectIdentifiers does not have member field 'org.bouncycastle.asn1.ASN1ObjectIdentifier xmss_SHAKE128_512ph'

### ISSUE THREAD

**Issue by juziys** [shred/acme4j#161]
![image](https://github.com/user-attachments/assets/c583cf92-aea4-4cbf-bd29-9184186b6e72)

**Comment by shred** [comment]
Please check if you have a consistent set of BouncyCastle dependencies in your project (same versions, no mixed `jdk15on` and `jdk18on` etc).

**Comment by shred** [comment]
Closing this issue. Feel free to reopen if it was not caused by mixed BouncyCastle dependencies.
