### ISSUE TITLE
ClientTest.java: attempts can be 0 and challenge.getStatus() can be Status.VALID at the same time

### ISSUE THREAD

**Issue by jm009** [shred/acme4j#19]
In
org.shredzone.acme4j.ClientTest.java

in Method
public void fetchCertificate(Collection<String> domains) throws IOException, AcmeException

in the code

```
            while (challenge.getStatus() != Status.VALID && attempts-- > 0) {
                if (challenge.getStatus() == Status.INVALID) {
                    LOG.error("Challenge failed... Giving up.");
                    return;
                }
                try {
                    Thread.sleep(3000L);
                } catch (InterruptedException ex) {
                    LOG.warn("interrupted", ex);
                }
                challenge.update();
            }
            if (attempts == 0) {
```

the last line should probably be changed to

`if (challange.getStatus() != Status.VALID) {`

because attempts can be 0 and challenge.getStatus() can be Status.VALID... (if I get it right...)

**Comment by shred** [comment]
Well, it's an edge case. The 10 attempts was just a random choice to avoid an endless loop. But you are right, the last attempt always fails even if the status just became VALID. I used your proposed fix. Thank you!
