### ISSUE TITLE
Test DNS challenge

### ISSUE THREAD

**Issue by shred** [shred/acme4j#2]
DNS challenge is implemented, but untested. I am waiting for a bug to be fixed in boulder (see https://github.com/letsencrypt/boulder/pull/1295).

**Comment by wteiken** [comment]
Is this the reason dns challenges are not enabled on the "v01" server?  They are enabled on the staging server (and working fine there).

**Comment by shred** [comment]
Thanks... I just tested the DNS challenge on the staging server, and it was working fine with acme4j.

The bug in boulder was fixed quite recently, so maybe the fix has not yet been deployed to the production server. However I can only guess as I am not directly involved in Let's Encrypt.
