### ISSUE TITLE
Request: add example for using cert in a web server

### ISSUE THREAD

**Issue by npomfret** [shred/acme4j#21]
Sorry, this isn't an issue but a request.

I'm having trouble using the downloaded x509 cert in an embedded undertow web server.  Was wondering if it would be possible to add some examples of how to use the certificates once they've been downloaded.  The [ClientTest](https://github.com/shred/acme4j/blob/master/acme4j-example/src/main/java/org/shredzone/acme4j/ClientTest.java) example was very useful.

The crux of the issue is that I need to create an SSLContext object for a server.  There's plenty of opinion out there on how to do this but so far I've failed to get it working.

**Comment by shred** [comment]
I'm sorry for my late reply. I haven't found a solution for creating an SSLContext, but I also haven't investigated too deeply.

If you have found a way to create it, I will gladly add examples to the documentation.

**Comment by npomfret** [comment]
Thats ok.  I gave up in the end and used nginx along with letsencrypt which seems to have worked well.
