### ISSUE TITLE
How to get Certificates from Registration?

### ISSUE THREAD

**Issue by porunov** [shred/acme4j#23]
Hello,
First of all I want to thank you for this project. It is just awesome.

I have a small issue. When I try to get certificates from registration it always get 0 certificates even if my domains are already verifyed and I downloaded them. 

Also the same problem with Authrization. Registration gets me 0 Authrizations always. 

I am using Letsencrypt as my provider.

Do you know if it is the problem with letsencrypt or I do something wrong?

Sincerely,
Alexandr

**Comment by shred** [comment]
Do you mean the methods `Registration.getAuthorizations()` and `Registration.getCertificates()`? _acme4j_ implements these methods as they are documented in the ACME protocol. However _Let's Encrypt_ does not currently provide this information, so the result is always empty.

**Comment by porunov** [comment]
Yes, those methods. I see. Thank you for your help!

Sincerely,
Alexandr

**Comment by shred** [comment]
You're welcome! :smile:
