### ISSUE TITLE
How to set tomcat ?

### ISSUE THREAD

**Issue by panlanghao** [shred/acme4j#25]
HI,I would like to ask a question.
I got six files(chain.crt,domain.crt,domain.csr,domain.key,domain-chain.crt,user.key) after running "acme4j-example" .
Which files can be used for generating .jks?

**Comment by muffl0n** [comment]
Check https://www.mulesoft.com/tcat/tomcat-ssl
But using Apache, nginx or similar as a reverse proxy that handles the HTTPS requests will be a less painful solution.

**Comment by shred** [comment]
I also found this documentation: https://community.letsencrypt.org/t/how-to-use-the-certificate-for-tomcat/3677/2

And a more general discussion about how to get certificates into the Java keystore: https://community.letsencrypt.org/t/how-to-get-certificates-into-java-keystore/25961

I hope it helps. I also prefer the reverse proxy solution, so I haven't tested it myself... :wink:
