### ISSUE TITLE
Adding Subject to certificate :

### ISSUE THREAD

**Issue by preethamshyam7** [shred/acme4j#27]
Hi ,

Here is my certificate which is generated.

Certificate [
[
  Version: V3
  **Subject:** SERIALNUMBER=ff74f801146029188f9fe0b241e9c65afc06, CN=www.iconectivteam.com
  Signature Algorithm: SHA256withRSA, OID = 1.2.840.113549.1.1.11

  Key:  Sun RSA public key, 2048 bits
  modulus: 

In this I need to add a value to subject column. The value is a static string. How can i add and what is the code to add subject to the certificate.

**Comment by shred** [comment]
You can add the subject to the CSR. If you use _acme4j_'s `CSRBuilder`, there are methods like `setOrganization()` for that purpose.

However, as the certificate is only domain validated, Let's Encrypt will only keep the CN (and SAN), and ignore everything else from the CSR's subject.

**Comment by preethamshyam7** [comment]
Hey, Thanks. But i got another task.

I need to add an custom OID in CSR builder and the steps to add an OID in csr builder is in the following link.

https://support.quovadisglobal.com/kb/a471/inserting-custom-oids-into-openssl.aspx

Do you have any idea in adding these as java codes.

**Comment by shred** [comment]
I'm afraid this is out of scope for _acme4j_. However, you might want to have a look at the `CSRBuilder` source, especially at the `sign()` method.
