### ISSUE TITLE
Adding new Extention

### ISSUE THREAD

**Issue by preethamshyam7** [shred/acme4j#28]
Hi Shred,

Im trying to add a new OID TN authorization List which is not supported by Boulder Lets encrypt right now. So, Im trying to change the codes in boulder to accept this TN OID. But before that I have to make some changes in CSR builder to invoke this new OID "1.3.6.1.5.5.7.1.26".

![image](https://cloud.githubusercontent.com/assets/26324704/24180993/3cf07fdc-0ede-11e7-8530-aed12dd797c2.png)

Is this fine or i need to make changes else where. Kindly advice on this.

Thanks in advance.

**Comment by shred** [comment]
It looks okay, but I don't know your goal, and actually I also don't know a reason why I should dig deeper on this issue. Please understand that this is the _acme4j_ bug tracker and not a forum for Boulder or Bouncy Castle.

**Comment by preethamshyam7** [comment]
Thanks Shred !
