### ISSUE TITLE
Parsing certificate

### ISSUE THREAD

**Issue by preethamshyam7** [shred/acme4j#29]
Hi,

The certificate which is generated as the following error. I hope this extension is not getting parsed. May I know which class in acme client is trying to parse the certificate?

<Certificate Extensions: 2

[1]: ObjectId: 1.3.6.1.5.5.7.1.26 Criticality=false
**Extension unknown: DER encoded OCTET string =**
0000: 04 25 30 23 A0 14 16 08 33 39 20 61 62 20 32 36 .%0#....39 ab 26
0010: 16 08 32 31 20 63 36 20 30 31 A1 0B 16 06 31 32 ..21 c6 01....12
0020: 33 34 35 36 02 01 01>

**Comment by shred** [comment]
Yes, the certificate is parsed to an `X509Certificate` object, which works fine for certificates generated by _Let's Encrypt_.

In _acme4j_ v0.10 I made a minor change that should help you. `Registration.requestCertificate()` now returns a `Certificate` object even if the certificate was not parseable. You can invoke `Certificate.getLocation()` to get the server side URI of the certificate, and then download the certificate from there yourself by a standard HTTP request.
