### ISSUE TITLE
Unable to get details of a failed authorization.

### ISSUE THREAD

**Issue by dernasherbrezon** [shred/acme4j#35]
Details are must have when it comes to configuring DDNS -> Port forwarding -> Nginx flows. They are available at:

> { ... , "error":{"type":"urn:acme:error:unauthorized","detail":"Invalid response from..."} ... }

I'm using version 0.11

**Comment by shred** [comment]
The details should be available if you invoke the `getMessage()` method of the exception.

**Comment by dernasherbrezon** [comment]
Unfortunately, there is no exception thrown. I'm executing ```challenge.update();``` in the ```while``` loop and checking ```challenge.getStatus() == Status.INVALID```.

According to the https://github.com/shred/acme4j/blob/32bfe3207743519eefae4eb40a1c12eb64495169/acme4j-client/src/main/java/org/shredzone/acme4j/challenge/Challenge.java#L163 response simply stored in the private variable. Can you:
  * throw exception if updating challenge has an error, OR
  * provide separate method to the challenge to get the error?

**Comment by shred** [comment]
Ah, I see... Yes, I will add a method where you can get the error state of a Challenge from.

**Comment by shred** [comment]
The new method is called `Challenge.getError()`. It is released in v0.12, which is available at Maven Central shortly. Thank you for the feature request. :Smile:
