### ISSUE TITLE
No ACME provider found for acme://letsencrypt.org/staging

### ISSUE THREAD

**Issue by Fabian95qw** [shred/acme4j#36]
Good day. 
I'm trying to implement the acme4j into a Starface (http://www.starface.de/de/index.php)

The Starface has a great Module System, which allows to load additional libraries, and classes in runtime.

I've written and pre-tested all the code in eclipse, and it works fine. 

Once loaded into the running System i already run into a problem when trying to create the session.

java.lang.IllegalArgumentException: No ACME provider found for acme://letsencrypt.org/staging

`
	at org.shredzone.acme4j.Session.lambda$new$2(Session.java:91)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.shredzone.acme4j.Session.<init>(Session.java:91)
	at org.shredzone.acme4j.Session.<init>(Session.java:63)
	at nucom.module.letsencrypt.session.RegisterSession.execute(RegisterSession.java:90)
	at de.vertico.starface.module.core....... //This part of the Stacktrace is no longer relevant
`

Line 90 in my Code is just:

` 
Session S = new Session("acme://letsencrypt.org/staging", SessionKP);
`

The Target Platform is :
OS: Centos
Version: 6.8 Final
Java-SE: 1.8.0_144
Java HotSpot: 64 Bit Server 25.144

Sadly i cannot figure out the issue, i tested DNS/Firewall related problems, but everything seems fine.

Any ideas?

Sincerly

Fabian95qw

**Comment by dernasherbrezon** [comment]
> This part of the Stacktrace is no longer relevant

Actually it is. Could you post non-formatted full stack trace? I was able to issue valid certificate using this url.

**Comment by shred** [comment]
acme4j uses the Java `ServiceLoader` to load the ACME providers. It seems that the respective configuration file is missing in your setup.

Please make sure that the file `META-INF/services/org.shredzone.acme4j.provider.AcmeProvider` is available in your class path. You will find this file in the `src/main/resources` directory of this project.

**Comment by Fabian95qw** [comment]
Hello Again

I solved the Problem yesterday by implementing the whole Code into a runnable, and invoking it.

> Please make sure that the file  META-INF/services/org.shredzone.acme4j.provider.AcmeProvider  is available 

Yea i checked. The file was there, but i as i already  suspected in previous Projects, the Module Classloader may ignores the meta-inf Folder, when loading classes/libraries. 

I Implemented the Runnable which communicates with the Module System trough  Localhost Connection, and just exchange the Data between the two running Java app's that way.

~ Problem Resolved.

**Comment by codemonstur** [comment]
I had the same error. 

The problem was that the code uses a java.util.ServiceLoader to find the providers, and the ServiceLoader uses the context classloader in the current thread. This classloader was not the class loader I was loading the jar with. Solution was to rewrite the jar loading code to call `Thread.currentThread().setContextClassLoader(classLoader);`.

**Comment by Fabian95qw** [comment]
When i updated the library to stay compliant with AcmeV2 i was able to directly use the libraby with the Module, without any issues, or having to modify the classloader.
