### ISSUE TITLE
Setting email for renewals

### ISSUE THREAD

**Issue by adamtg** [shred/acme4j#48]
Is there a way to setup the email to get renewal messages? 

thank you very much.

**Comment by shred** [comment]
There is no way to set renewal notifications.

You can read the expiry date of your certificate via `X509Certificate.getNotAfter()`, and renew the certificate a couple of days before expiry.

**Comment by BryceStevenWilley** [comment]
Apologies for resurrecting a closed issue, but I've been looking into this recently.  I'm assuming that you mean that `acme4j` has no way to set renewal notifications, but from what I understand, CA's like LetsEncrypt can and do send renewal notifications.  And that using other ACME clients like [certbot](https://github.com/certbot/certbot/blob/5b5a2efdc9d53492fa1d9c04b845fc5d5415cce3/certbot/certbot/_internal/client.py#L255) can get you those. I've been using `acme4j` for a few months, and the `mailto:` contact is attached to the account I'm using, but haven't received any emails from LetsEncrypt, and unfortunately it doesn't look like there's a way to test the notifications. I tried looking around for any differences between what certbot is doing with the supplied email and what acme4j is doing with it, but I couldn't tell, so I figured I might ask here.

**Comment by shred** [comment]
The ACME protocol itself does not provide means to set up renewal notifications via email. All you can do is adding contact addresses to your account, but the purpose is not specified any further.

Let's Encrypt [says here](https://letsencrypt.org/docs/expiration-emails/) that all you need to do is to give an email address at account registration, and they will automatically start to send you notifications 20 and 7 days before expiration.

I also had a look a the [Boulder source code](https://github.com/letsencrypt/boulder), and found an `expiration-mailer` tool there. It just uses the `mailto:` address that is connected to your account.

So all I can tell is that you _should_ get the notification mails, unless you unsubscribed from them.

**Comment by shred** [comment]
I have just set an email address to my account via acme4j, and already got a renewal notification mail from Let's Encrypt a few hours later. So there's nothing more to do than to make sure that there is at least one valid `mailto:` address set in your account, and have at least one certificate that will expire in 20 days or less.

Have you checked the usual suspects (typo in email address, spam folder, etc)?

**Comment by BryceStevenWilley** [comment]
Thanks for confirming this! It did take me until now to confirm that I got a reply, and it looks like my issue was that I had been using an account key that didn't yet have any email in the `mailto:` address, and I had been incorrectly assuming that `AccountBuilder::addEmail()` would add an email to an existing account, and it didn't seem to do that. Instead, I needed to get the already logged in account and call `account.modify().addEmail().commit();`

Sorry for the late reply, and thanks for the assistance!

**Comment by shred** [comment]
Thank you for your feedback! Yes, `AccountBuilder` will only create new accounts, but won't modify existing accounts. `account.modify()` is the correct way to change the email addresses of existing accounts. I will point that out in the documentation.
