### ISSUE TITLE
Add "title" member to the Problem object

### ISSUE THREAD

**Issue by marsangr** [shred/acme4j#49]
Field is optional according to 7807, but would still useful:
```
    /**
     * Returns a short, human-readable summary of the problem type.
     */
    public String getTitle() {
        return problemJson.get("title").asString();
    }
```

**Comment by shred** [comment]
I'm not sure about this request. The examples in the ACME specs make no use of the `title` field, so this getter is likely to return `null` in almost all cases. If someone would need to read that field, he could still invoke `problem.asJSON().get("title").asString()`.

Do you have a special use case in mind?

**Comment by marsangr** [comment]
We were thinking of encoding there the values of the right column ("description") of the table in
https://tools.ietf.org/html/draft-ietf-acme-acme-09#section-6.6

A "type" is not descriptive enough and "detail" wouldn't be the appropriate field for this, since it is thought to have details for the particular problem instance (e.g. "Invalid underscore in DNS name 'example.com'").

**Comment by shred** [comment]
Actually a good idea. Added in commit 22975dc8. Thanks!
