### ISSUE TITLE
The version of acme4j-client in online document is wrong: "2.0-SNAPSHOT"

### ISSUE THREAD

**Issue by MulticolorWorld** [shred/acme4j#52]
Document says the version of acme4j-client is 2.0-SNAPSHOT([here](https://shredzone.org/maven/acme4j/index.html)), but acme4j-client:2.0-SNAPSHOT dosn't exist in maven central repository at that time.

**Comment by shred** [comment]
Yes... _acme4j_ is currently in a transition phase. acme4j 2.0 is for the ACMEv2 protocol, which is not ready for production yet. At the moment, _Let's Encrypt_ only provides a staging server for ACMEv2. 

The latest version for production is 0.14, which is available on maven central. The documentation can be found [here](https://shredzone.org/maven/acme4j-acmev1/index.html).

I'm sorry for the confusion.

**Comment by MulticolorWorld** [comment]
I want to use 2.0-SNAPSHOT for testing wildcard certifilate. I confused because it look like usable new version jar from maven central at document. I thought using this for build myself.
It's okay to close this issue. Thanks to reply.

**Comment by shred** [comment]
For testing wildcard certs, you'll have to build the master branch yourself at the moment.

I'll keep the bug open. The documentation is probably confusing other developers, too.

**Comment by shred** [comment]
I've mentioned the 2.0-SNAPSHOT in the project's README.
