### ISSUE TITLE
need same domain auth when wildcard domain auth

### ISSUE THREAD

**Issue by MulticolorWorld** [shred/acme4j#53]
When I need to authorization one domain(example.com) and this wildcard domain(*.example.com), Order give two Authorization object. But these Authorization Object is to same domain auth(to example.com). 
Do I need to complete both authorization?

**Comment by shred** [comment]
The ACME server sends two authorizations. One authorization is for `example.com`, and accepts all three kind of challenges. The other authorization is for `*.example.com` and only accepts dns-01.

To be on the safe side, you should perform the first authorization. After that, check the status of the second authorization. If the second one isn't VALID, you'll also have to complete that one.

It's not _acme4j_, the behavior comes from the ACME server.

**Comment by MulticolorWorld** [comment]
I understand. Thanks.

**Comment by cpu** [comment]
One other note: If you look closely the Let's Encrypt server sends back one authorization with a (_non-standard, not present in the ACME specification_) field `"wildcard":"true"` for the authorization with only a DNS-01 challenge. That's another small signal that it isn't the same authorization as the one with a DNS-01, HTTP-01, and TLS-SNI-01 challenge for the base domain that isn't a wildcard.

Hope that helps!
