### ISSUE TITLE
External account binding overwriting kid for subsequent requests?

### ISSUE THREAD

**Issue by robaman** [shred/acme4j#54]
Hello!

Using the current latest version of the master branch (https://github.com/shred/acme4j/commit/622d5795ec416a5d8930e1697c1fb918c08eec0a)

I'm trying to use acme4j's external account binding support and having some trouble with the kid getting set to the externalAccountBinding kid in subsequent requests (for example newOrder), instead of the account URL/kid generated by the server.

For example I have some test code that does external account binding with:
keyIdentifier: 242 and a hmac key.

This is an excerpt of the relevent parts of the debug log:
```
[main] DEBUG org.shredzone.acme4j.connector.DefaultConnection - POST http://localhost:15000/acme/new-order
[main] DEBUG org.shredzone.acme4j.connector.DefaultConnection -   Payload: {"identifiers":[{"type":"dns","value":"example.com"}]}
[main] DEBUG org.shredzone.acme4j.connector.DefaultConnection -   JWS Header: {"nonce":"_xRuseKZ4V8qIP9J-l5PL0o0gxFZ1jCJQoS19fxfWh0","url":"http://localhost:15000/acme/new-order","kid":"242","alg":"RS256"}
[main] DEBUG org.shredzone.acme4j.connector.DefaultConnection - HEADER null: HTTP/1.1 400 Bad Request
[main] DEBUG org.shredzone.acme4j.connector.DefaultConnection - Result JSON: {"type":"urn:ietf:params:acme:error:accountDoesNotExist","detail":"Account 242 not found.","status":400}

org.shredzone.acme4j.exception.AcmeServerException: Account 242 not found.
```

This is what the log looks like after I've applied my patches:

```
[main] DEBUG org.shredzone.acme4j.connector.DefaultConnection - POST http://localhost:15000/acme/new-order
[main] DEBUG org.shredzone.acme4j.connector.DefaultConnection -   Payload: {"identifiers":[{"type":"dns","value":"example.com"}]}
[main] DEBUG org.shredzone.acme4j.connector.DefaultConnection -   JWS Header: {"nonce":"MJxLH0m4HRm_TTAr5FVAfjlSLV1yBlHIJJB2loGjoNs","url":"http://localhost:15000/acme/new-order","kid":"http://localhost:15000/acme/acct/ddf3711393f599180a5648a03f3a7bda1ece81df22a9cc336a6fce75d279bee4","alg":"RS256"}
```

I've made the following changes to be able to solve it for me, but I would like to hear your thinking about the changes I've made, before I submit an eventual PR.

https://github.com/robaman/acme4j/commit/6bd9a490790760061b793d4af3d929e9329014d4
https://github.com/robaman/acme4j/commit/dff96dace56dedc1162f694ec7c02c75d8f31e67

Thanks!

regards,
Robert Kästel

**Comment by shred** [comment]
Thank you for the comment, Robert.

My interpretation of the ACME specs, and especially of the "External Account Binding" section, is that the "kid" field must always be set to the key identifier provided by the CA, when using external account binding. This is the behavior your are seeing in your report.

But I see that the specs are ambiguous here. I could not find any hints in the appropriate acme specs' pull requests. Do you have other documents that clarify the contents of the "kid" field?

**Comment by robaman** [comment]
This is how I interpret it:

In section 7.3.5 (https://ietf-wg-acme.github.io/acme/draft-ietf-acme-acme.html#rfc.section.7.3.5)

"The ACME client then computes a binding JWS to indicate the external account holder’s approval of the ACME account key. The payload of this JWS is the account key being registered, in JWK form. ".

"account key being registered" means I should supply a new public key for the account in JWK form for to this request.

It's talking about two different key types. 
"key identifier from CA" and "MAC using MAC key from CA" - This is the mac key.
"same as in "jwk" above" and "account key" - This is the public key of the client generated account key pair.

Maybe @cpu can give us his opinion?

**Comment by robaman** [comment]
Just sent an email to the ACME IETF mailing list.
https://mailarchive.ietf.org/arch/msg/acme/_j_xfYp9rlLeAtOWtSuQ-UtX3k0

**Comment by shred** [comment]
Thanks... But I am not sure if we are talking about the same problem now.

_acme4j_ always uses the account key pair for signing. The MAC is only used once, to sign the inner JWS of the external account binding. It seems we both agree on that.

If I understand your issue correctly, we both disagree on the content of the "kid" field. It is used in the inner JWS of the external account binding, and also in every JWS protected header, except of `new-account` and `revoke-cert`. The "kid" field usually contains the account URL (see ACME specs: "This field must contain the account URL received by POSTing to the new-account resource."), and you also seem to expect to find the account URL in that field.

However, when using external account binding, my interpretation of the ACME specs is that if external account binding is used, the "kid" field always contains the key identifier provided by the CA. Because otherwise it would not make much sense to name this field "kid" in the JWS protected header, and not just "accountUrl" or so.

I will try to post a follow-up in the mailing list.

**Comment by shred** [comment]
Ah... Thinking about it again, I see where I'm wrong. The "kid" field is related to the JWS, not to the ACME protocol. Then it makes perfect sense to use different "kid"s for the account key and the MAC key.

Let's wait for the answer to my follow-up, but I guess I will gladly accept your PR. :smile:

**Comment by robaman** [comment]
Sorry for the confusion. Saw we got a clarification on the mailing list now. Will get a proposal PR for you early next week.

**Comment by shred** [comment]
OK, thank you!

**Comment by robaman** [comment]
PR is here: https://github.com/shred/acme4j/pull/55

What do you think?

**Comment by shred** [comment]
Merged it. Thank you.
