### ISSUE TITLE
[Future Request] Refactoring at Kotlin language

### ISSUE THREAD

**Issue by MulticolorWorld** [shred/acme4j#56]
Kotlin is a better Java on JVM language. I love kotlin. I think refactor acme4j at kotlin and do pull request.
If I request changes refactoring at kotlin, is it possible to merge this request?

**Comment by shred** [comment]
It is already possible to _use_ acme4j in Java, Kotlin, Scala, Groovy, Ceylon, etc... For this reason, I see no advantage in porting the project itself to a different JVM language. I'm sorry.
