### ISSUE TITLE
Release acme4j v2

### ISSUE THREAD

**Issue by marcomsousa** [shred/acme4j#58]
**ACMEv2 protocol.**

The oficial endpoint to ACMEv2 already are online: https://acme-v02.api.letsencrypt.org/
Can you please release the acme4j v2 version , if isn't the final version, an beta version will be ok.

**Comment by shred** [comment]
There have been some last minute fixes, but I'm running a few final tests now. acme4j v2 will be available in the next hours.

**Comment by shred** [comment]
_acme4j_ v2.0 is now released and available at GitHub. It has also been deployed to Maven Central already, and should be available there very soon.
