### ISSUE TITLE
PKIX path building failed

### ISSUE THREAD

**Issue by kornelc** [shred/acme4j#71]
Hi,

I'm trying to get the client example code to work:

findOrRegisterAccount crashes with 
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

The URL that triggers it is https://acme-staging-v02.api.letsencrypt.org/directory.
(So I'm using v2)

Am I supposed to configure the JVM with any specific key store on the client side as well to make things work? According to posts on line, this error usually indicates that the client side certificate was not properly configured.

Apologies if this was covered in the docs somewhere. But I could not find any reference to this when I looked.

Thanks in advance for any help!

**Comment by shred** [comment]
You need at least Java 8 Update 101, as the required CA keys have been added there.

Are you using Debian Stretch? The OpenJDK keystore seems to be broken there. I "resolved" it by moving my OpenJDK docker image to Alpine, so I don't know details about that issue. You could try Oracle Java and see if the error persists.

**Comment by shred** [comment]
Okay... Just reopen this bug if the problem still occurs after the upgrade. :smile:
