### ISSUE TITLE
Java 9+

### ISSUE THREAD

**Issue by shred** [shred/acme4j#75]
_acme4j_ offers a basic Java 9 support, by having Automatic-Module-Name defined since v2.7.

There will be full module-info definitions in a future version. However, this depends on [a change in jose4j](https://bitbucket.org/b_c/jose4j/issues/132/automatic-module-name).

**Comment by olegvakulenko** [comment]
Hi!

I may be wrong, but `jose4j` made the necessary changes.
https://www.slf4j.org/news.html

> 6th of August, 2019 - Release of SLF4J 1.7.27
Added Automatic-Module-Name in MANIFEST.MF files in various SLF4J artifacts

**Comment by shred** [comment]
Not quite... Your change is in slf4j, but I need the change in jose4j. :wink:

The patch has been merged into jose4j's master branch already, but has not been released yet.

**Comment by shred** [comment]
All dependencies are now having at least an automatic module name. Commit b32f03b2 removed the last obstacle: JSR305 null-safe annotations have been replaced by SpotBugs annotations. JSR305 was using the `javax.annotations` package, which lead to split packages.

Commit 610b9366 adds module-info definitions and creates a multi-release jar.

The next acme4j release will now have full Java 9 module support. :tada:
