### ISSUE TITLE
Implement generation of self-signed development certificates

### ISSUE THREAD

**Issue by Menzani** [shred/acme4j#76]
It would be nice to have an API to generate self-signed certificates to be used [for development purposes](https://letsencrypt.org/docs/certificates-for-localhost/).
It could even support making root and leaf certificates.
It might require Bouncy Castle, so I'd place it into the `acme4j-utils` module.

**Comment by shred** [comment]
Thank you for the input! Yes, it would be useful. And in fact I am also going to need something like this for my unit testing framework that is coming soon.

I will have a deeper look at it and then get back to you.

**Comment by shred** [comment]
I have added test CA certification methods in commit b5550a3f:

* `CertificateUtils.createTestRootCertificate()` creates a self-signed root certificate.
* `CertificateUtils.createTestIntermediateCertificate()` creates an intermediate certificate that is either issued by the root CA or another intermediate CA. You can build a certificate chain this way.
* `CertificateUtils.createTestCertificate()` creates a certificate that uses some of the parameters given in the CSR, and that is signed by a root or intermediate CA.

You can find code examples in the unit tests at `CertificateUtilsTest`.

The methods will be available in the next acme4j version 2.8.
