### ISSUE TITLE
Feature request: Vert.x integration

### ISSUE THREAD

**Issue by lukehutch** [shred/acme4j#79]
It would be really nice if acme4j could be easily set up in a Vert.x pipeline, serving the ACME requests directly from the Verticle, and causing Vert.x' certificates to be dynamically reloaded when needed.

Some relevant info:

https://github.com/xkr47/vertx-acme4j/issues/1

https://github.com/eclipse-vertx/vert.x/issues/2870

I don't think it would take a lot of code to implement this, but I think the acme4j team would have a much better idea about it...

**Comment by shred** [comment]
I'm afraid that I'm not having the time to become acquainted with the Vert.x framework.

If there are concrete changes to acme4j that would help with a Vert.x integration, please send PRs or describe them in separate issues, and I will see what I can do.
