### ISSUE TITLE
Clarification on required libraries

### ISSUE THREAD

**Issue by jvanhill** [shred/acme4j#84]
The project's README claims that acme4j only requires jose4j and slf4j, but it appears that Bouncy Castle is also required.

Could this be updated?

Additionally, is it required to use Bouncy Castle as a JCA provider? Testing I have done so far does not seem to indicate it is required, but it may be only because I have not hit paths that require the BC JCA provider and / or the JVM I am using provides the crypto algorithms that acme4j is using.

**Comment by shred** [comment]
I'm not quite fond of the idea of having Bouncy Castle as a hard dependency. For this reason, `acme4j-client` is actually designed that it only requires jose4j and slf4j. All the parts requiring BC are moved to the `acme4j-utils` module.

If you use `acme4j-utils`, you need BC as dependency. You should also have its provider installed as JCA, unless you only use crypto algorithms that are supported by your JVM out of the box. You are right, I should really point that out in the README.

But technically, you can only use `acme4j-client` (without BC) if you have other means of creating key pairs and CSRs, and if you stay with the crypto algorithms that are supported by the JVM.

**Comment by doom369** [comment]
AcmeClient example uses:

```
import org.shredzone.acme4j.util.CSRBuilder;
import org.shredzone.acme4j.util.KeyPairUtils;
```

So I believe in most cases users need to include utils and thus Bouncy Castle as well.
By the way current BC version is outdated.

**Comment by shred** [comment]
I have changed the README. It now states that BC is a requirement, unless you have other means of creating key pairs and CSRs.

Please reopen this issue if you think that it is not resolved by the change.

I have also updated all dependency versions now. :wink:
