### ISSUE TITLE
AcmeException: Failed to pass the challenge for domain

### ISSUE THREAD

**Issue by incube8r** [shred/acme4j#86]
Using `acme4j` fails to generate certificate with this error:

    org.shredzone.acme4j.exception.AcmeException: Failed to pass the challenge for domain www.
    mysampledomain123.com, ... Giving up.

I manually checked the challenge file and got 

    http://www.mysampledomain123.com/.well-known/acme-challenge/jU--PkDrn5tDZw2RN6NNJHbPD00ovHFkLFvN3mJdeQX

Inside the file:

    jU--PkDrn5tDZw2RN6NNJHbPD00ovHFkLFvN3mJdeQX.tuMr-UijwpsJ1KVZkdWTYgodWZ2SxxKdB7_CMAAEfpg

And here's the complete HTTP response header:

    Accept-Ranges: bytes
    Connection: keep-alive
    Content-Encoding: gzip
    Content-Type: text/plain;charset=iso-8859-1
    Date: Sun, 16 Feb 2020 14:15:22 GMT
    Server: nginx/1.14.0 (Ubuntu)
    Transfer-Encoding: chunked
    Vary: Accept-Charset, Accept-Encoding, Accept-Language, Accept
    X-Powered-By: Divroll
    X-RateLimit-Limit: 1000
    X-RateLimit-Remaining: 999
    X-RateLimit-Reset: 0

I'm wondering whether the problem is with the HTTP response headers or the content itself. 
Any ideas would be appreciated.

**Comment by shred** [comment]
If you are using the acme4j example code, the message "Failed to pass the challenge for domain www.mysampledomain123.com, ... Giving up." means that after 30 seconds, the challenge state still hasn't changed to `VALID` or `INVALID`.

There can be a number of reasons. Maybe `Challenge.trigger()` wasn't invoked? Maybe the CA server is getting network timeouts while trying to access your challenge file?

You can increase the number of retries by changing the `int attempts = 10;` line in the example.

Also, the acme4j log output may show what is happeining.

**Comment by incube8r** [comment]
I think I have a hint now, this code:

```
// Poll for the challenge to complete.
        try {
            int attempts = 20;
            while (challenge.getStatus() != Status.VALID && attempts-- > 0) {
                LOG.info("CHALLENGE ATTEMPTS: " + attempts);
                // Did the authorization fail?
                if (challenge.getStatus() == Status.INVALID) {
                    throw new AcmeException("Challenge failed... Giving up.");
                }

                // Wait for a few seconds
                Thread.sleep(5000L);

                // Then update the status
                challenge.update();
            }
        }
```

And the ` Thread.sleep(5000L);` is halting the servlet and thus the servlet is not able to respond. 
Since the same servlet is server the challenge file. 

Now I have to figure out how to actually convert this into Servlet-friendly code.

**Comment by shred** [comment]
The example code is only meant to be a simple example. It also only offers a very simple error handling.

In a Servlet context, you could for example use a separate thread, or `@Async` in a Spring environment. The best way IMO would be to run the certificate handling in a separate service that is decoupled from the servlet stuff.

**Comment by shred** [comment]
I'm closing this bug. If I can help you further, please reopen it.
