### ISSUE TITLE
Add support for SAN certs (multiple domains)

### ISSUE THREAD

**Issue by axelfontaine** [shred/acme4j#9]

**Comment by shred** [comment]
Actually, it is already added and works fine for me. Each domain needs to be authorized individually. After that, create a CSR with SAN of all domains. You can use the CSRBuilder (in the acme4j-utils module) for that:

CSRBuilder csrb = new CSRBuilder();
csrb.addDomain("example.org");
csrb.addDomain("www.example.org");
// you can add even more domains...
csrb.sign(domainKeyPair);
URI certUri = client.requestCertificate(account, csrb.getEncoded());

I have successfully retrieved SAN certs that way.

**Comment by axelfontaine** [comment]
Awesome! Thank you! You could probably even just copy paste this and add it to the docs :-)

Great work BTW! Small single-purpose library. Solves one problem and solves it well. Almost no dependencies and great documentation. This is how things should be :+1:

**Comment by shred** [comment]
The example was copied [from the docs](https://shredzone.org/maven/acme4j/usage/certificate.html#Request_a_Certificate)... ;-) But indeed, I could explain a little more how to get SAN certs.

**Comment by axelfontaine** [comment]
I had actually read that page and somehow missed it. Sorry about the trouble and thanks again!

**Comment by shred** [comment]
No trouble at all! Thank you for your positive feedback!
