### ISSUE TITLE
Example url not found

### ISSUE THREAD

**Issue by olegvakulenko** [shred/acme4j#90]
Hi!

On page "acme4j"
https://shredzone.org/maven/acme4j/index.html

in section "Modules"
https://shredzone.org/maven/acme4j/index.html#modules

link "an example code"
https://shredzone.org/maven/acme4j/acme4j-example/apidocs/src-html/org/shredzone/acme4j/example/ClientTest.html

results in error "404 Not Found"

**Comment by shred** [comment]
Thanks! It got broken when I migrated the build environment to Java 9+. I will look into it.

**Comment by shred** [comment]
The example can be found [here](https://shredzone.org/maven/acme4j/example.html) now.
