### ISSUE TITLE
Does acme4j support “alternate” link relation?

### ISSUE THREAD

**Issue by doom369** [shred/acme4j#92]
Hello. I have a question avove. Do you aware it?

Here more info about it - **https://community.letsencrypt.org/t/issuance-on-r3-vs-x3-is-this-configurable/138496**

**Comment by shred** [comment]
Sure it does. :smile:

I recently wrote a blog article about it: https://shred.zone/cilla/page/448/access-alternate-certificates-with-acme4j.html

Let's keep this issue open for a while, so other users may find it.

**Comment by doom369** [comment]
@shred you're awesome. Thanks!

**Comment by shred** [comment]
Let's Encrypt found a way to extend Android compatibility until 2024: https://letsencrypt.org/2020/12/21/extending-android-compatibility.html
