### ISSUE TITLE
how to hold Order and Authorization for a while

### ISSUE THREAD

**Issue by yang229** [shred/acme4j#93]
Due to business relations, the order and authorization need to be temporarily saved.
I can get the json string with getJSON method, but how I get the object from the json string.

**Comment by shred** [comment]
The JSON string only represents your current local state of the resource, so it is usually not very useful to save it.

The recommended way is to use the resource URL:

```java
URL orderLocation = order.getLocation();
URL authLocation = authorization.getLocation();
```

To restore the object, use the respective bind method of `Login`:

```java
Login login = ...
Order restoredOrder = login.bindOrder(orderLocation);
Authorization restoredAuth = login.bindAuthorization(authLocation);
```

Also see: https://shredzone.org/maven/acme4j/usage/login.html#resource-binding

If you want to temporarily store the current state (e.g. to share it between two server instances), you can also use serialization: https://shredzone.org/maven/acme4j/usage/login.html#serialization . However I recommend to share the location and use the bind methods.

**Comment by yang229** [comment]
Thanks. I'v got the solution.
